language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
      before_install:
        - sudo apt-get update --fix-missing
        - sudo apt-get update -qq
        - sudo apt-get install -y
            freeglut3-dev
            g++
            libasound2-dev
            libcurl4-openssl-dev
            libfreetype6-dev
            libjack-jackd2-dev
            libx11-dev
            libxcomposite-dev
            libxcursor-dev
            libxinerama-dev
            libxrandr-dev
            mesa-common-dev
            ladspa-sdk
            webkit2gtk-4.0
            libgtk-3-dev
        - sudo apt-get update
        - sudo apt-get update --fix-missing
      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sleep 3  # give xvfb some time to start
      script:
        - $TRAVIS_BUILD_DIR/install/linux_build

    - os: osx
      osx_image: xcode9.4
      script:
        - $TRAVIS_BUILD_DIR/tests/mac_tests

    - os: windows
      env:
        - MSBUILD_EXE="C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe"
      script:
        - $TRAVIS_BUILD_DIR/tests/windows_tests.bat
